### ISSUE TITLE
chrome.tabs.create returns a wrong tab to callback

### ISSUE THREAD

**Issue by SuselMan** [avast/topee#7] opened 2019-09-09 09:54 UTC
1) I call ```chrome.tabs.create({
      url: 'some url',
      active: true
    }, (tab) => {// some code here})```
2) `tab` in callback is the tab which was active before create method calling.
Expected result
`tab` has to be just created tab.

**Comment by pavelstudeny** [comment] 2019-09-10 07:22
Does it reproduce 100% or sometimes?

**Comment by SuselMan** [comment] 2019-09-10 13:06
100% in my case

**Comment by pavelstudeny** [comment] 2019-09-16 07:43
chrome.tabs.create currently flawlessly works only on a browserAction click, because when this was implemented, https://developer.apple.com/documentation/safariservices/sfsafaripage/3075408-getcontainingtab wasn't available. This will be fixed once the target SDK is increased to 10.14.4+.

**Comment by pavelstudeny** [comment] 2020-11-07 18:17
should be much better in the 3.x.x releases

**Closed by pavelstudeny** 2020-11-07 18:17 UTC
