### ISSUE TITLE
`carthage bootstrap` error: Dependency "topee" has no shared framework schemes

### ISSUE THREAD

**Issue by duzun** [avast/topee#9] opened 2019-09-29 21:21 UTC
![Screen Shot 2019-09-29 at 2 17 38 PM](https://user-images.githubusercontent.com/321424/65839665-2d492780-e318-11e9-8714-388bf590869e.png)

**Comment by Shinisaru** [comment] 2019-09-30 08:57
Support of swift 5.1 will be added in next release (soon).

**Comment by duzun** [comment] 2019-09-30 15:56
Thanks @Shinisaru!
What can I do meanwhile to be able to work on the project on Xcode 11?
Should I install an older version of swift?

**Comment by pavelstudeny** [comment] 2019-09-30 17:07
Topee 1.x with Swift 4.2 has worked well until now.

**Comment by Shinisaru** [comment] 2019-10-01 11:58
@duzun you can try adding sources via submodule or smth and topee framework project as a dependency on your build target. There is nothing swift 4.2 specifics, it should build.
We are planning on releasing 5.1 support tomorrow (experimental release if failing)

**Comment by duzun** [comment] 2019-10-02 05:30
TYVM, I’ll try to figure it out and awaiting the new release :)

**Comment by duzun** [comment] 2019-10-03 11:39
I must be doing something wrong, but with Topee v2.0.0 I have the same issue.
![topee 2 0 0 fail](https://user-images.githubusercontent.com/321424/66123823-8f8d7b00-e5eb-11e9-9a20-18aa0d0ce69f.png)

**Comment by pavelstudeny** [comment] 2019-10-03 15:21
that’s expected, 2.0.0 was an experiment whether just changing swift to 5.1 would do the job and it does not. stay tuned. any luck with switching to swift 4.2 with topee 1.x, by the way?

**Comment by duzun** [comment] 2019-10-03 16:06
No luck :( 
I'm not familiar with Xcode and Swift and I guess I'm doing something stupid.

I've managed to download and install Swift 4.2, added to the PATH `/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin`, 
so that `swift --version` shows 
`Apple Swift version 4.2.1-dev (LLVM 4ba03d9389, Clang 78aa734eee, Swift f4134ebef6)
Target: x86_64-apple-darwin18.7.0`

but `carthage bootstrap` with topee v1.5.1 throws the same error and sais 	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)."

I would appreciate any help!

**Comment by duzun** [comment] 2019-10-03 16:11
I'm trying to do what @Shinisaru has suggested, it sounds like an easy thing, but I have to read a lot to find out how to do that :)

**Comment by duzun** [comment] 2019-10-03 17:56
I've managed to compile topee v1.5.1 with `make build` in the repo, using Swift 5.1.
I also had to install `npm`, which was not obvious from the readme.

**Comment by Shinisaru** [comment] 2019-10-06 20:40
yeah, we should add a make rule for dependencies, i'll tend to it.
Anyways, what I suggested was for you to drag 'n drop topee project file to the files tree of your project in xcode, that navigate to your app's build target, go to build settings tab and there under first `Dependencies` section add Topee.framework.
That way topee will build automatically before,  building your app.
Anyway, we finally have a setup ready for building topee 2.0.1 tomorrow, so you can check up new release tomorrow.
Also, notifications from here go to my personal email which i don't check regularly, if you find yourself in need of speedy help, try reaching me on telegram: @onmyojo, i'm way more reactive there.

**Comment by pavelstudeny** [comment] 2019-10-07 11:48
Fixed in 2.0.1 - use that with Swift 5.1. Stay on 1.5.1 if you keep using Swift 4.2.

**Closed by pavelstudeny** 2019-10-07 11:48 UTC

**Comment by duzun** [comment] 2019-10-07 17:47
TYVM @Shinisaru, your suggestions showed me the right direction :), and the `make build` command worked for me. 
But I can't follow your instructions per se. I can not find the `Dependencies` section. It looks like some parts of the Xcode have changed in the latest version because not all screens/steps from the instructions in the wizard.md are exactly the same in the new UI.

After playing around and trying things, I've created an AppEx project in Xcode right from the beginning, opposed to the wizard.md, which suggests only the option of creating the Mac App than adding the AppEx to it.

The part with `Copy files` task on Build Phases is not needed, it breaks the build.

There are some other small differences too.

I have also tried to `make build` topee v2.0.0, but with no luck due to an error:

```log
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "6H4HRTU5E3" with a private key was found. (in target 'Topee' from project 'Framework')
```

I've managed to compile and install the AppEx to Safari, and I'm stuck with the logging of the background script now...

**Comment by Shinisaru** [comment] 2019-10-08 09:06
@duzun we initially have not intended topee to be built from sources, 2.0.1 should be working for you via carthage, does it?
Anyways, as you mention instructions could take a revision as it seems fo xcode 11.
We will tend to it when we have time

**Comment by pavelstudeny** [comment] 2019-10-08 17:15
by the way, have a look at the documentation, e.g. https://github.com/avast/topee/blob/master/documentation/xcode_bootstrap.md if you needed to build your own project in xcode

**Comment by duzun** [comment] 2019-10-09 05:30
Yes @Shinisaru, v2.0.1 builds fine with `carthage bootstrap`!

@pavelstudeny I think I should have read that doc from the very beginning. I could have started the project from the Demo app :), but now I have a working setup already.

Thank you for your help!

**Comment by adi** [comment] 2020-04-02 06:38
Hi!
It seems v2.3.0 doesn't build with carthage bootstrap and Swift 5.2!
Thanks!

**Comment by pavelstudeny** [comment] 2020-04-12 16:27
Seems to be caused by https://github.com/Carthage/Carthage/issues/2887 . A fix is already available on master. Hopefully, a new carthage version with this fix will be released soon.

**Comment by liamcharmer** [comment] 2020-05-13 14:24
Do we just have to wait for the carthage release or is there anything we can do??

**Comment by pavelstudeny** [comment] 2020-05-18 09:04
As @priyanshuchauhan points out at https://github.com/avast/topee/issues/15#issuecomment-613247418 , it's probably quite straightforward to use the _master_ Carthage.
By the way, judging from the previous Carthage releases, a new one can be expected quite soon.
